specVersion: 0.0.1
description: "Talisman subql"
repository: "https://github.com/willMorph/talisman-subql.git"
schema: ./schema.graphql
network:
  endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7690000 #7567818
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
